### ISSUE TITLE
New Members

### ISSUE THREAD

**Issue by CreaturePhil** [FakeSloth/zoa#1]
@Lord-Haji @HoeenCoder

Since you guys send a bunch of PRs to Showdown-Boilerplate, are you guys interested in helping me with this chat app project? I will help you guys get familiar with the codebase and you get to learn how to build an app similiar to Pokemon-Showdown from scratch!

**Comment by Lord-Haji** [comment]
I am
@CreaturePhil
sorry for let reply was out of github for a few days

**Comment by HoeenCoder** [comment]
Sorry about the very late reply @CreaturePhil I've been busy (and will remain so).

I'm interested in working on this, so count me in! Just remember I have alot to do atm, so I might not help out a huge amount but I will be sure to pull weight.
